apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::506828864174:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-2WCPOTHQL9IQ
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::506828864174:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-30T21:09:52Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1768"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 8aecf317-e68b-47e3-88e0-502d484c10c7
